### ISSUE TITLE
adding Footer enhancing the UI

### ISSUE THREAD

**Issue by devxMani** [gupta-ritik/ExpenseTracker#11]
add GSOC ext and hacktoberfest label to it

**Comment by gupta-ritik** [comment]
Can you share the design of the footer

**Comment by devxMani** [comment]
![image](https://github.com/user-attachments/assets/0cb2b4e8-53aa-4006-94f2-cb49a946b0a9)

**Comment by devxMani** [comment]
@gupta-ritik project is running but not showing any data you have any input ........
![image](https://github.com/user-attachments/assets/93966041-b635-4e21-9322-ff3b4560d4d1)

**Comment by gupta-ritik** [comment]
Complete the footer

**Comment by devxMani** [comment]
@gupta-ritik i think data is not fetching

**Comment by gupta-ritik** [comment]
complete the footer part otherwise i will unassigned you
