### ISSUE TITLE
Adding scroll Bottom to up Navigation button

### ISSUE THREAD

**Issue by devxMani** [gupta-ritik/ExpenseTracker#12]
ADD GSOC EXT and Hacktoberfest label to it

**Comment by Zahhiiir** [comment]
Hi @devxMani I think I'm unable to replicate the issue on my localhost
because page seems fixed and I'm looking forward to add scroll buttom to up button
![ExpenseTracker_Screenshot 2024-10-04 220330](https://github.com/user-attachments/assets/89cc8936-ded7-48a3-8a5d-17a7383f61f3)
