### ISSUE TITLE
Adding All Contributors' Profile Photos

### ISSUE THREAD

**Issue by souvikpramanikgit** [gupta-ritik/ExpenseTracker#14]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

Hey! @gupta-ritik  I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it
![image](https://github.com/user-attachments/assets/34a80dad-11d1-4f08-87b7-8097544f6912)

**Comment by gupta-ritik** [comment]
complete it

**Comment by gupta-ritik** [comment]
did you started ??

**Comment by souvikpramanikgit** [comment]
yes, wait for 5 minute i send the pull request
