### ISSUE TITLE
Deploy 

### ISSUE THREAD

**Issue by vijaychandra1910** [gupta-ritik/ExpenseTracker#2]
![Screenshot 2024-10-02 024426](https://github.com/user-attachments/assets/d4723680-f320-44fb-a700-3aa97184df9c)
The local server are different for different users so you can host in any platform where user and contributors can explore your website.

**Comment by gupta-ritik** [comment]
Can you explain it in the details

**Comment by Harshitraaaj** [comment]
he means that deploy your website in online platform so that its it live and working condition. Give this role to me i can host this platform i online and make it live .

**Comment by gupta-ritik** [comment]
Complete it asap

**Comment by Harshitraaaj** [comment]
Srry , I am bzy on another porject so i didnt pay attention on this one . I'll look into this and complete ASAP . could you label this under hactoberfest too

**Comment by Harshitraaaj** [comment]
since this project is already deployed in vercel , I have fix few indentation in the files and generate a pull req . pull req : #15
