### ISSUE TITLE
Add login/Signup for the Website

### ISSUE THREAD

**Issue by haseebzaki-07** [gupta-ritik/ExpenseTracker#24]
Add user login and signup to the application for robust user-management.

**Comment by Maheshwari-Love** [comment]
@haseebzaki-07 complete the task within 3-4 day

**Comment by ChampGupta** [comment]
If this issue is not resolved please assign it to me
<img width="1470" alt="Screenshot 2024-10-10 at 9 20 11 PM" src="https://github.com/user-attachments/assets/293dcef3-d673-4b9e-a31d-6217fe863238">

**Comment by Maheshwari-Love** [comment]
@haseebzaki-07 any update?

**Comment by haseebzaki-07** [comment]
hey @Maheshwari-Love I am facing this issue.

https://github.com/user-attachments/assets/8c5105d3-4592-461f-b102-10442a62cbb5
