### ISSUE TITLE
Lets Work on this Project

### ISSUE THREAD

**Issue by Sameeratweb** [gupta-ritik/ExpenseTracker#3]
i would like to work on this Project. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by Maheshwari-Love** [comment]
> i would like to work on this Project. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

hi @Sameeratweb find the issues or some task you want to do, we will be assigning you those tasks to cover up...

**Comment by geetanjalidubey9** [comment]
I read your code and I really want to work on it. please assign this task to me.
