### ISSUE TITLE
Addition of Dockerfile.

### ISSUE THREAD

**Issue by unknown91tech** [gupta-ritik/ExpenseTracker#32]
@gupta-ritik Addition of the docker file will help in smoother running of the project locally.

**Comment by gupta-ritik** [comment]
Complete it

**Comment by gupta-ritik** [comment]
have you started ..

**Comment by unknown91tech** [comment]
yes almost there, will create a pr in about a hour or so

**Comment by gupta-ritik** [comment]
Is completed

**Comment by unknown91tech** [comment]
@gupta-ritik I have created a pr , can you check it

**Comment by unknown91tech** [comment]
@gupta-ritik I have added a new pr with the docker file , can you review it and tell me if there are any changes to be made

**Comment by unknown91tech** [comment]
@gupta-ritik I have added a pr
