### ISSUE TITLE
[FEATURE] A Chatbot which guides user according to need

### ISSUE THREAD

**Issue by Peart-Guy** [gupta-ritik/ExpenseTracker#39]
The chatbot will have a feature of Natural Language which will easily omit user's grammatical mistakes and spelling mistakes in chat input. The admin can train the chatbot whenever needed in a .json file.

-->The chatbot will have its back end in Python with modules like PyTorch, NumPy, etc. and and a basic front end in CSS and JS and HTML

I would like to work on this issue
Name: Ankan
Participant Role: Contributor , GSSOC-24 Extd

Screenshots:

![Screenshot 2024-10-09 023835](https://github.com/user-attachments/assets/57cacf9b-74ba-4df6-ab71-fc4c53c653dc)

**Comment by gupta-ritik** [comment]
Try to complete asap

**Comment by Peart-Guy** [comment]
> Try to complete asap

sure will complete it very soon

**Comment by gupta-ritik** [comment]
@Peart-Guy progress ??

**Comment by Shariq2003** [comment]
> Try to complete asap

@gupta-ritik assign this to me, I will complete this within one day

**Comment by Peart-Guy** [comment]
> @Peart-Guy progress ??

@gupta-ritik 
I am facing a issue since the features in the site require to Log In to create a session. But how do i log in in your site

**Comment by Shariq2003** [comment]
@gupta-ritik please assign this to me.

**Comment by Peart-Guy** [comment]
> > @Peart-Guy progress ??
> 
> @gupta-ritik I am facing a issue since the features in the site require to Log In to create a session. But how do i log in in your site

@gupta-ritik  My chatbot is almost ready and just needs testing  kindly look into the above matter as this is what is stopping me to test. 
Thank You
