### ISSUE TITLE
Bugs in whole website

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [gupta-ritik/ExpenseTracker#45]
![image](https://github.com/user-attachments/assets/75f797dd-86f3-4dc7-9de1-fcd1f99b5b81)

you can assign me to resolve the issues in frontend and also resolve the issues in the backend when calling the API call but frontend is not responding

**Comment by Sehrishzarin** [comment]
yes, also the repeated log out needs to be fixed

**Comment by Kuldeepsinghrajpoot** [comment]
can you assign me to resolve this issues
