### ISSUE TITLE
Fix Side Drawer

### ISSUE THREAD

**Issue by shubhagarwal1** [gupta-ritik/ExpenseTracker#48]
Currently side drawer In mobile view has inconsistent placement of the lists 
![image](https://github.com/user-attachments/assets/8084a679-dc7a-4818-b170-cc7279a3982d)

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.

**Comment by shubhagarwal1** [comment]
hey @gupta-ritik i can fix this tonight if you assign me this task
