### ISSUE TITLE
Add the husky to the project

### ISSUE THREAD

**Issue by Ameerjafar** [gupta-ritik/ExpenseTracker#49]
currently we don't have husky in our project if we add this one the code will automatically formatted when someone try to commit their code This is easy to review the code for the maintainer at the same time we can maintain the code fromat.

**Comment by Ameerjafar** [comment]
@gupta-ritik  can you assign me this issue in the tag of gssoc and hacktoberfest.

**Comment by Maheshwari-Love** [comment]
@Ameerjafar you can start working on it

**Comment by Ameerjafar** [comment]
@Maheshwari-Love can you add hacktoberfest tag

**Comment by Ameerjafar** [comment]
@Maheshwari-Love can you review my pr
