### ISSUE TITLE
Adding backend for login/signup

### ISSUE THREAD

**Issue by tarunkumar2005** [gupta-ritik/ExpenseTracker#56]
Adding backend for login/signup

I will be using express, mongodb and other necessary libraries to work with and create a professional and well maintained backend for the login, signup, logout, and verify token.

@gupta-ritik Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by gupta-ritik** [comment]
@tarunkumar2005 go ahead
