### ISSUE TITLE
Fix the all Syntax Error and bugs also

### ISSUE THREAD

**Issue by gupta-ritik** [gupta-ritik/ExpenseTracker#6]
there are many syntax error in this project

**Comment by ParasY1724** [comment]
@gupta-ritik  Please assign this task to me under gssoc-ext , i have already started and fixed some syntax errors. Thanks!!

**Comment by gupta-ritik** [comment]
Fix all the syntax error

**Comment by ParasY1724** [comment]
@gupta-ritik This issue should be closed.Is something i missed?

**Comment by gupta-ritik** [comment]
some issues with syntax error are not remove

**Comment by Bhavya445** [comment]
can u plss assign this to me
