### ISSUE TITLE
Updating Readme File

### ISSUE THREAD

**Issue by Hridyesh03** [gupta-ritik/ExpenseTracker#7]
I want to add  other sections to the readme file like contributors and want to improve the overall readability of the file.
Kindly assign me this under gssoc extend 2024 under valid tags.

**Comment by gupta-ritik** [comment]
Complete it asap

**Comment by Hridyesh03** [comment]
It will be done by tomorrow  had my finals today

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by AnujSaha0111** [comment]
Solved in #29
