### ISSUE TITLE
Adding frontend for signin/signup  and integrating it with the backend

### ISSUE THREAD

**Issue by Siddhi-sahu** [gupta-ritik/ExpenseTracker#75]
i will implement frontend and integrate it with backend from the recently merged Backend pull request, i will make sure the frontend looks clean, look for any issues in the Backend and work on user authentication for different endpoints

@gupta-ritik @Maheshwari-Love  Assign this to me under appropriate labels:)

**Comment by gupta-ritik** [comment]
trying to solve this issues

**Comment by Siddhi-sahu** [comment]
@gupta-ritik working on it!

**Comment by Siddhi-sahu** [comment]
@gupta-ritik it looks like sign-in/signup is up on your website but they dont seems to be working, what do you want me to do?

**Comment by Siddhi-sahu** [comment]
@gupta-ritik it seems like frontend is already up, and people are already working on the bug. So you can assign other people

**Comment by PriyanshuValiya** [comment]
@gupta-ritik  Assign me this issue, i will implement it..
