### ISSUE TITLE
Successful signup

### ISSUE THREAD

**Issue by haseebzaki-07** [gupta-ritik/ExpenseTracker#80]
user signs up the website but no confirmation is displayed also the user should be redirected to the home page on successful signup/login
![Screenshot 2024-10-18 202049](https://github.com/user-attachments/assets/32c05a47-6747-402b-8753-79d384095beb)

**Comment by gupta-ritik** [comment]
@haseebzaki-07 solve the problem

**Comment by haseebzaki-07** [comment]
@gupta-ritik sure
