### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by jainaryan04** [gupta-ritik/ExpenseTracker#82]
Feature: Add dark mode using a user defined hook and custom styling to all the pages. The user will be able to switch between the modes via a toggle switch in the navbar.
@gupta-ritik please add gssoc-ext and hacktoberfest-accepted labels and assign it to me so I can start working on it.

**Comment by jainaryan04** [comment]
@Maheshwari-Love can you please change it to level 3 ? I will have to modify css for all the pages. It will take time

**Comment by Maheshwari-Love** [comment]
Go ahead...

**Comment by Maheshwari-Love** [comment]
> Go ahead...

Level will be decided on your code and overall quality do the best...no need to mention for upgrading the level...also a small suggestion, don't just play for levels, learn from open source 😃...

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love can you please change it to level 3 ? I will have to modify css for all the pages. It will take time

@jainaryan04 Level will be decided on your code and overall quality do the best...no need to mention for upgrading the level...also a small suggestion, don't just play for levels, learn from open source 😃...

Go ahead...and you can discuss if any where you stuck or any new idea you have ...

**Comment by jainaryan04** [comment]
@Maheshwari-Love I have added it to sign up and sign in
Let me know if it's fine, then I will continue with the other pages.

**Comment by Maheshwari-Love** [comment]
Add out put screenshot

**Comment by jainaryan04** [comment]
@Maheshwari-Love 

![image](https://github.com/user-attachments/assets/33965031-279f-4b2a-8a65-a765f8331919)

![image](https://github.com/user-attachments/assets/707199fc-3e09-4a3c-983e-e8cc8634b12e)

**Comment by jainaryan04** [comment]
@Maheshwari-Love 
I am not able to login
![Uploading image.png…]()
