### ISSUE TITLE
Adding OAuth for quick and fast login and register

### ISSUE THREAD

**Issue by LitZeus** [gupta-ritik/ExpenseTracker#83]
Adding the OAuth for login and register will save time and efforts to access the app, being all the information secure and fast processing!

Multiple login ways like github, google, meta can be added as per the requirement

Will also be looking the frontend and backend integration for quick login methods
@gupta-ritik @Maheshwari-Love Assign this to me under appropriate labels:)

**Comment by ayesha-firdaus** [comment]
Sir i would like to work on this please assign me.
