### ISSUE TITLE
[Feature] Add a toast

### ISSUE THREAD

**Issue by ak3264114** [gupta-ritik/ExpenseTracker#9]
### Problem Description
- There is currently no toast notification system in place to handle and display messages to users effectively.

### Proposed Solution
- I will integrate **React Hot Toast** to provide a proper way of displaying success, error, and information messages to the users, improving overall user experience and feedback.

Please assign this issue to me under hacktorber fest and gssoc-ext

**Comment by gupta-ritik** [comment]
Add some image for the above issues

**Comment by ak3264114** [comment]
Here is sample toast i will be using for notifying user

![image](https://github.com/user-attachments/assets/aadd62e6-ba59-444b-97ff-db5c125268b7)
