### ISSUE TITLE
BUG: No rerouting to home page after signup and signin

### ISSUE THREAD

**Issue by aryadevesh** [gupta-ritik/ExpenseTracker#95]
As you can see in the network tab of inspect, After I click signup the response code came out to be 200 but the page stays on Signup as well as on Signin too which is an issue. 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/68ce073c-69db-43de-bd39-bf5e33adb35b">
<img width="943" alt="image" src="https://github.com/user-attachments/assets/53869eaf-f7bc-4e97-9c63-c7dc77522fcb">

**Comment by ayesha-firdaus** [comment]
Sir i would like to work on this issue please assign me
