### ISSUE TITLE
Add "Show Password" Feature to Login Page

### ISSUE THREAD

**Issue by saras-69** [gupta-ritik/ExpenseTracker#99]
Here’s an example of an issue for adding a Show Password Feature on the login page:

Title: Add "Show Password" Feature to Login Page

Description
The login page currently requires users to enter their password without the option to view it. To improve user experience and reduce typing errors, we need to implement a "Show Password" feature that allows users to toggle the visibility of their password.

Acceptance Criteria
UI Design:

Add a clickable "eye" icon (or similar) inside the password input field that allows users to toggle between showing and hiding the password.
The icon should change state depending on whether the password is visible or hidden.
Functionality:

When the "eye" icon is clicked, the input type should change between "password" and "text" to either hide or show the password.
Ensure that the password visibility toggle works smoothly and does not affect form validation.

![Screenshot 2024-10-23 010315](https://github.com/user-attachments/assets/d0e616e6-bd64-4aaa-aec3-b8c86c4f8010)

**Comment by Manashgoswamii** [comment]
can you assign it to me?
